### ISSUE TITLE
puppetserver 7.15.0, 7.14.0 & 7.12.0 docs are missing

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/puppet-docs#1138]
## Describe the Bug
https://www.puppet.com/docs/puppet/7/server/release_notes.html  doesn't list changes for 7.15.0, 7.14.0 & 7.12.0 

## Expected Behavior

I expect a detailed changelog, if possible with linked github/public jira tickets. Instead 7.15.0 is missing completely, and 7.14.0/7.12.0 have no information at all.

## Environment
 - Version [e.g. 1.27.0]
 - Platform [e.g. Ubuntu 18.04]

**Comment by lisarobertson** [comment]
Moving forward, we will include the sentence: _This release includes minor updates that do not change functionality for users._
