### ISSUE TITLE
PE Server install page changes

### ISSUE THREAD

**Issue by spotter-puppet** [puppetlabs/puppet-docs#1142]
https://www.puppet.com/docs/pe/2023.6/install-pe-using-installer-tarball

Section 1 (Verify the installation package) starts with "These steps are only required if your organization requires you to verify authenticity before installing packages."  However, the very first step is to download the installation package (the tar file from the PE download site).  Either this section should be retitled "Obtain and verify the installation package" and the first sentence should be moved to the verification steps, or there should be two sections - "Obtain the installation package" and "Verify the installation package".  If this is done, the duplicated instructions under "Install from tarball" can be removed to reduce confusion.

The _wget_ and _curl_ examples should state that quotes are required if using the puppet.com download.cgi links.

In the "Install from tarball" section, the tar command needs to have **-z** included for installation packages downloaded from the puppet.com download.cgi links, since the files are stored in gzip format.

**Comment by lisarobertson** [comment]
This issue has been fixed and will be published in the next release.
