### ISSUE TITLE
puppet 8 release notes have missing/incorrect jira links

### ISSUE THREAD

**Issue by bugfood** [puppetlabs/puppet-docs#1143]
The puppet 8 changelog has some incorrect links. For example here:
https://www.puppet.com/docs/puppet/8/release_notes_puppet#enhancements_puppet_x-8-3-0-PUP-11429
...the jira link is:
https://perforce.atlassian.net/browse/PUP-11429
...but should be:
https://puppet.atlassian.net/browse/PUP-11429

More recent entries have no links at all for jira issue numbers. For example here:
https://www.puppet.com/docs/puppet/8/release_notes_puppet#resolved_issues_puppet_x-8-5-1-PUP-11985

Thanks,
Corey

**Comment by cthorn42** [comment]
@parkerdleach

**Comment by lisarobertson** [comment]
The Jira instance at puppet.atlassian.net has been archived and we are now using the Jira instance at perforce.atlassian.net. All relevant issues were migrated to that instance.

In some cases, entries will not contain Jira issue numbers.
