### ISSUE TITLE
docs mention nonexisting puppetserver subcommand

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/puppet-docs#1144]
## Describe the Change You Would Like
From https://www.puppet.com/docs/puppet/7/config_file_oid_map :
> Run `puppetserver ca print` to see changes made in custom_trusted_oid_mapping.yaml immediately without a restart.

But `puppetserver ca print` isn't a valid command.

**Comment by lisarobertson** [comment]
Docs have been updated and will be published with the next release.
