### ISSUE TITLE
PE release notes have non release date

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/puppet-docs#1147]
## Describe the Bug

Hi, https://www.puppet.com/docs/pe/2021.5/release_notes_pe.html has no information when the PE releases actually happened.

## Expected Behavior

I expect a release date in release notes.

**Comment by lisarobertson** [comment]
As of release 2021.7, we have been including the Month and Year of release in our release notes. The 2021.5 version of the documentation is no longer being updated.
