### ISSUE TITLE
include_legacy_facts on puppet 8 defaults to false

### ISSUE THREAD

**Issue by maxadamo** [puppetlabs/puppet-docs#1150]
The documentation states that `include_legacy_facts` defaults to `true` on puppet 8: 

https://www.puppet.com/docs/puppet/8/configuration.html#include-legacy-facts

This was true on puppet 7, but on puppet 8 the default is false.

**Comment by kenyon** [comment]
This isn't the only error. https://github.com/puppetlabs/puppet/issues/9312 would hopefully fix this.

**Comment by lisarobertson** [comment]
Has been fixed and will be published with next OSP release.
