### ISSUE TITLE
Puppet Agent compatibility matrix is wrong / misses information

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/puppet-docs#1151]
## Describe the Bug

https://www.puppet.com/docs/puppet/8/primary_agent_compatibility says agent 7 works only on puppetserver 7 and agent 8 only on puppetserver 8. I did some internal testing for PE customers and Agent 7 and 8 worked without issues on puppetserver 6/7/8. Can you please update the table or list which components aren't compatible?

## Expected Behavior

a compatibility matrix that tells me why something isn't compatible.

## Environment
 - Version [e.g. 1.27.0]
 - Platform [e.g. Ubuntu 18.04]

**Comment by J-Hunniford** [comment]
The table has been updated: https://www.puppet.com/docs/puppet/8/platform_lifecycle#primary-agent-compatibility

When writers investigated, engineering explained that although old servers (like 7.x) might work with newer agents (like 8.x), such combinations aren't tested or supported so customers using them could run into problems.
