### ISSUE TITLE
Documentation links point to old versions

### ISSUE THREAD

**Issue by spotter-puppet** [puppetlabs/puppet-docs#1152]
Meier
  11:15 AM
The links on this page https://www.puppet.com/docs/puppet/8/plugins_in_modules#adding-plug-ins-to-a-module all point to ancient doc versions

**Comment by IngridaCazers** [comment]
The links are now updated on the documentation preview server. The new links will be visible when the documentation is published with the next product release.

**Comment by IngridaCazers** [comment]
Done.
