### ISSUE TITLE
puppetserver 8.2 lacks information

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/puppet-docs#1153]
## Describe the Change You Would Like

In https://github.com/puppetlabs/puppetserver/commit/28fbc56ce483aed223ff929ff928bd4fca258454 the default value for automatic certificate renewal got changed. The changelog doesn't list this: https://www.puppet.com/docs/puppet/8/server/release_notes#puppet-server-820

Also the whole autorenew configuration is not documented at https://www.puppet.com/docs/puppet/8/server/config_file_puppetserver

**Comment by IngridaCazers** [comment]
I discussed this question with development. I learned that the update is not documented because it is an internal update that does not affect standard functionality for open source Puppet users. Closing this issue.

**Comment by bastelfreak** [comment]
Sorry, but how is https://github.com/puppetlabs/puppetserver/commit/28fbc56ce483aed223ff929ff928bd4fca258454 just an internal update?
