### ISSUE TITLE
Outdated diagram on the page The roles and profiles method

### ISSUE THREAD

**Issue by mrsteffenjo** [puppetlabs/puppet-docs#1154]
## Describe the Change You Would Like
I would like the text or [diagram](https://www.puppet.com/docs/puppet/7/roles_and_profiles_overview_server.png) to be changed so that they match up on page. Illustrated in the attachment.
https://www.puppet.com/docs/puppet/7/the_roles_and_profiles_method.html#configuring_roles_and_profiles

![image_720](https://github.com/puppetlabs/puppet-docs/assets/1678112/12697c34-f634-4f91-9a77-d6c0de484ebe)

**Comment by IngridaCazers** [comment]
The requested updates were implemented and will be published in the next release. Closing this ticket.
