### ISSUE TITLE
Update supported agent platforms for puppet 7 and 8

### ISSUE THREAD

**Issue by joshcooper** [puppetlabs/puppet-docs#1156]
Please update the supported agent platforms for puppet 7 and 8

## Puppet 7
https://www.puppet.com/docs/puppet/7/system_requirements#supported_operating_systems-packaged-platforms

### Add
- [ ] Debian 12 (x86_64)
- [ ] Debian 12 (ARM)
- [ ] Red Hat Enterprise Linux 6 (i386)
- [ ] Red Hat Enterprise Linux 6 (x86_64)
- [ ] Red Hat Enterprise Linux 7 (x86_64)
- [ ] Red Hat Enterprise Linux 8 (x86_64)
- [ ] Red Hat Enterprise Linux 8 (ppc64le)

### Modify
- [ ] Red Hat Enterprise Linux 9 (x86_64) currently it just says `9` without an architecture

### Remove
- [ ] Ubuntu 24.04 (x86_64) (This won't be available until July)
- [ ] Red Hat Enterprise Linux 9 FIPS (that is PE only)

## Puppet 8
https://www.puppet.com/docs/puppet/8/system_requirements#supported_operating_systems-packaged-platforms

### Add
- [ ] Red Hat Enterprise Linux 7 (x86_64)
- [ ] Red Hat Enterprise Linux 8 (x86_64)
- [ ] Red Hat Enterprise Linux 8 (ppc64le)

### Modify
- [ ] Debian 12 aarch64 and ARM different names for the same architecture. I think Debian prefers the `aarch64` naming convention
- [ ] macOS 14 x86_64 and Intel are different names for the same architecture. Please drop the `Intel` variation.
- [ ] Red Hat Enterprise Linux 9 (x86_64) currently it just says `9` without an architecture
- [ ] Ubuntu 20.04 AARCH and 22.04 ARM64 should be `aarch64`

## Remove
- [ ] Ubuntu 24.04 (x86_64) (This won't be available until July)
- [ ] Red Hat Enterprise Linux 9 FIPS (that is PE only)

**Comment by IngridaCazers** [comment]
This issue has been addressed. The updated system requirements will be published in the next releases.
