### ISSUE TITLE
generate_request action is missing from online docs

### ISSUE THREAD

**Issue by joshcooper** [puppetlabs/puppet-docs#1159]
## Describe the Change You Would Like

The `ssl` man pages for puppet7 and 8

https://www.puppet.com/docs/puppet/8/man/ssl
https://www.puppet.com/docs/puppet/7/man/ssl

Are missing the `generate_request` action, which is documented in

https://github.com/puppetlabs/puppet/blob/56d07e923c9c7cfd1a9c4e8553ae30fcbd82ee25/man/man8/puppet-ssl.8#L45-L46

**Comment by lisarobertson** [comment]
This issue was fixed and the documentation was published as part of the Puppet 8.8.1 and 7.32.1 releases.
