### ISSUE TITLE
Legacy Fact $fqdn in current EPP Documentation

### ISSUE THREAD

**Issue by marcusdots** [puppetlabs/puppet-docs#1161]
## remove legacy fact `$fqdn` from documentation

The EPP templating documentation

https://www.puppet.com/docs/puppet/8/lang_template_epp.html

provides two examples of using facts in printing tags

    <%= $fqdn %>
    ServerName <%= $facts[fqdn] %>

The first line is considered legacy, the second line is embraced syntax. The documentation should drop the legacy to favor adoption of the new syntax.

**Comment by lisarobertson** [comment]
This issue was fixed and the documentation was published as part of the Puppet 8.8.1 and 7.32.1 releases.
