### ISSUE TITLE
Puppetserver upgrade documentation is wrong

### ISSUE THREAD

**Issue by iscb1962** [puppetlabs/puppet-docs#1162]
https://www.puppet.com/docs/puppet/7/upgrade_puppet_server.html 

states "The puppetserver package, in turn, depends on the puppet-agent package, and your node’s package manager automatically upgrades puppet-agent if the new version of puppetserver requires it.”

We used puppet itself to update the puppetserver package and it did not pull in the puppet-agent package which resulted in the puppetserver failing to start due to some gem dependencies missing.

Either the document is wrong or the documentation is wrong.   I'm going to raise this in both docs and bugs.

**Comment by mtaggart13** [comment]
Issue will be fixed in docs scheduled for release on Sept 10th.

**Comment by mtaggart13** [comment]
Issue will be fixed in docs scheduled for release on Sept 10th.
