### ISSUE TITLE
preprocess_deferred has the wrong default value for Puppet 8

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/puppet-docs#1166]
## Describe the Bug

https://www.puppet.com/docs/puppet/8/configuration.html#preprocess-deferred lists the wrong default value. It's `true` on Puppet 7 but `false` on Puppt 8.

See:
* https://github.com/puppetlabs/puppet/blob/8.6.0/lib/puppet/defaults.rb#L2105-L2114
* https://github.com/puppetlabs/puppet/blob/7.31.0/lib/puppet/defaults.rb#L2062-L2071

## Expected Behavior

`preprocess_deferred` should be documented as `false` for Puppet 8 and `true` for Puppet 7.

## Environment
 - Version [e.g. 1.27.0]
 - Platform [e.g. Ubuntu 18.04]

**Comment by joshcooper** [comment]
This will be fixed in https://github.com/puppetlabs/osp-docs/pull/347/files#diff-ab78ec9b49123c3684de845dafa770fef2344d5730e4756e4b7f54e5024160f3R1568

**Comment by joshcooper** [comment]
This is fixed see https://www.puppet.com/docs/puppet/8/configuration#preprocess-deferred
