### ISSUE TITLE
Puppet 8 docs say we support Scientific Linux 8, which doesn't exist

### ISSUE THREAD

**Issue by spotter-puppet** [puppetlabs/puppet-docs#1168]
https://www.puppet.com/docs/puppet/8/system_requirements#system_requirements
lists Scientific Linux 8 (x86_64, aarch64, and ppc64le).  However, Scientific Linux was cancelled after version 7, which was EOLed last month along with all of the other *EL7 OSes.  We should remove the reference to SL8, since it doesn't exist and would be an amazing feat for us to support!

**Comment by mtaggart13** [comment]
Issue will be fixed for the next release.
