### ISSUE TITLE
confining on structured facts isn't optimal

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/puppet-docs#1170]
## Describe the Change You Would Like

https://www.puppet.com/docs/puppet/8/custom_facts.html#configuring_facts-confining-facts suggests:

```ruby
confine 'os' do |os|
  os['family'] == 'RedHat'
end
```

but I think this is overly complicated and should be shortened:

```ruby
confine 'os.family' == 'RedHat'
```

**Comment by mtaggart13** [comment]
Issue will be fixed in docs scheduled for release on Sept 10th.
