### ISSUE TITLE
Theres no Puppet Enterprise Server package for RHEL 9 FIPS x86_64 systems. 

### ISSUE THREAD

**Issue by marcthestrong** [puppetlabs/puppet-docs#1171]
Currently, there are no package available for RHEL 9 x86_64 servers that are required to operate in FIPS mode. Although there is  a RHEL9 server package for x86_64, only RHEL 7 and RHEL 8 are supported for FIPS mode.

**Comment by kenyon** [comment]
This probably belongs at https://github.com/puppetlabs/puppet-enterprise_issues/issues/ instead.

**Comment by spotter-puppet** [comment]
Closing the docs issue since it has been asked in the PE project.
